Almost done debugging installer

diff --git a/bin/ld-import b/bin/ld-import
--- a/bin/ld-import
+++ b/bin/ld-import
@@ -14,6 +14,8 @@
 #   Fail2Ban from a directory or tarball.  Services will be stopped,
 #   configuration imported, and then services will be started again.
 #
+#   Currently running configuration will be exported if possible.
+#
 # OPTIONS:
 #   path | filename
 #      Path or filename to import data from
@@ -21,9 +23,12 @@
 #      Echos the commands that would be executed rather than executing them
 #   -h | --help
 #      Run help function and exit
+#   -n | --no-backup
+#      Does not attempt to backup current configuration
 #   -t | --tmp
 #      Default = /tmp
-#      Provide an alternate location to save current configuration
+#      Provide an alternate location to save current configuration, only
+#      relevant if passing a tarball to import
 #   -v | --verbose
 #      Output each line of the script after validations are parsed
 #
@@ -35,26 +40,27 @@ set -euo pipefail
 IFS=$'\n\t'
 
 # Values
+BACKUP=1
 DATE=`date +%Y%m%d%H%M%S`
-ETC=0
 DRY_RUN=''
-FILENAME="lockdown-$DATE.tar.gz"
+FILENAME=''
 ORIGIN="`pwd`"
-PERMANENT=0
-SAVE_PATH="`pwd`"
-TMP_LOCATION="/tmp/lockdown-$DATE"
+TARBALL=''
+TMP_LOCATION='/tmp'
+TYPE=''
 VERBOSE=0
+WORKING_DIR="lockdown-$DATE"
 
 # Help function
 help () { 
   echo "Description:"
-  echo "  Saves current configuration of IP Tables, IP Set and Fail2Ban as a set of"
-  echo "  files and directories in the directory specificed (or /etc when not set)."
-  echo "  If any of the services are not running, their existing configuration file"
-  echo "  from /etc will be used if it exists."
+  echo "  Restores previously exported (by Lockdown) configuration of IP Tables,"
+  echo "  IP Set and Fail2Ban.  An attempt will be made to back up the current"
+  echo "  configuration, but you will not be asked for confirmation to overwrite"
+  echo "  files."
   echo "Usage:"
-  echo "  `basename $0` [-d] [-h] [-p] [-v]"
-  echo "  `basename $0` [--dry-run] [--help] [--path /save/path] [--verbose]"
+  echo "  `basename $0` [-d] [-h] [-v]"
+  echo "  `basename $0` [--dry-run] [--help] [--verbose]"
   exit 0
 }
 
@@ -71,21 +77,23 @@ do
       DRY_RUN='echo'
       shift 1
     ;;
-      -e | --etc)
-      ETC=1
-      shift 1
-    ;;
       -h | --help)
       help
       shift 1
     ;;
-      -p | --path)
-      SAVE_PATH=$2
-      shift 2
+      -n | --no-backup)
+      BACKUP=0
+      shift 1
     ;;
       -t | --tmp)
-      TMP_LOCATION=$2
-      shift 2
+      if [ -d $1 ]
+      then
+        TMP_LOCATION=$2
+        shift 2
+      else
+        echo "Error: Invalid temporary location specified: $2"
+        exit 1
+      fi
     ;;
       -v | --verbose)
       VERBOSE=true
@@ -95,18 +103,25 @@ do
       echo "Error: Unknown option: $1" >&2
       exit 1
     ;;
-      *)  # No more options
-      break
+      *)  # Should be a filename or path
+      if [ -d $1 ]
+      then
+	TYPE='dir'
+        WORKING_DIR=$1
+        shift 1
+      elif [ -f $1 ]
+      then
+        TARBALL=$1
+	TYPE='file'
+        shift 1
+      else
+      then
+        echo "Error: Unknown target: $1" >&2
+        exit 1
+      fi
     ;;
     esac
 done
-
-# Check save path exists
-if [ ! -d "$SAVE_PATH" ]
-then
-  echo "Output location $SAVE_PATH could not be found, cannot continue"
-  exit 1
-fi
 
 # Check verbosity
 if (( VERBOSE ))
@@ -114,57 +129,54 @@ then
   set -v
 fi
 
-# Special case scenario
-if (( ETC ))
-then
-  $DRY_RUN iptables-save > /etc/sysconfig/iptables
-  $DRY_RUN ipset -S > /etc/ipset.conf
-  exit 0
-fi
+# Stop services
+$DRY_RUN service fail2ban stop
+$DRY_RUN service iptables stop
+$DRY_RUN service ipset stop
 
-if [ "/etc" -eq "$SAVE_PATH" ]
-then
-  echo "You must use ld-export -e or ld-export --etc to export to /etc"
-  help
-  exit 1
-fi
+# Kill services if necessary
+$DRY_RUN pidof fail2ban && $DRY_RUN pidof fail2ban | $DRY_RUN xargs kill -9
+$DRY_RUN pidof iptables && $DRY_RUN pidof iptables | $DRY_RUN xargs kill -9
+$DRY_RUN pidof ipset && $DRY_RUN pidof ipset | $DRY_RUN xargs kill -9
 
 # Backup currently saved configuration
-$DRY_RUN cd /etc
-$DRY_RUN tar czf "$SAVE_PATH/$FILENAME" \
-  iptables* \
-  ipset* \
-  fail2ban* \
-  lockdown*
+if (( BACKUP ))
+then
+  $DRY_RUN ld-export
+fi
 
-# Set up for running configuration export
-$DRY_RUN mkdir -p "$TMP_LOCATION"
-$DRY_RUN cd "$TMP_LOCATION"
-# Save IP Tables & IP Set rules to temp location
-$DRY_RUN iptables-save > iptables
-$DRY_RUN ipset -S > ipset.conf
-# Copy Fail2Ban configs to temp location
-$DRY_RUN /bin/cp -ar /etc/fail2ban .
-# Copy Lockdown configs to temp location
-$DRY_RUN /bin/cp -ar /etc/lockdown .
+# Set up temporary space if passed a tarball
+if [ $TYPE = 'file' ] && [ -f "$TARBALL" ]
+then
+  $DRY_RUN mkdir -p "$TMP_LOCATION/$WORKING_DIR"
+  $DRY_RUN cp $TARBALL "$TMP_LOCATION/$WORKING_DIR"
+  $DRY_RUN cd "$TMP_LOCATION/$WORKING_DIR"
+  $DRY_RUN tar xzf *.tar.gz
+elif [ $TYPE = 'dir' ] && [ -d "$WORKING_DIR" ] 
+  $DRY_RUN cd $WORKING_DIR
+fi
 
-# Tar them and move them to destination
-$DRY_RUN tar czf "$SAVE_PATH/$FILENAME" *
+# Copy files into place
+$DRY_RUN /bin/cp -rf etc/* /etc
+
+# Check for iptables backup from running config exports
+if [ -f iptables.bak ]
+then
+  $DRY_RUN iptables-restore < iptables.bak
+fi
+
+# Start services
+$DRY_RUN service fail2ban start
+$DRY_RUN service iptables start
+$DRY_RUN service ipset start
+
+# Test services
+$DRY_RUN ld-test
+
 # Clean up
-$DRY_RUN /bin/rm -rf "$TMP_LOCATION"
-# Move uncompressed files to save path
-$DRY_RUN cd "$ORIGIN"
-$DRY_RUN mv "$TMP_LOCATION" "$SAVE_PATH"
+if [ $TYPE = 'file' ]
+then
+  $DRY_RUN /bin/rm -rf $TMP_LOCATION/$WORKING_DIR
+fi
 
 exit 0
-
-
-
-# Execution commands
-# Unpack tarball to temp location
-# Archive current configs
-# Restore ipsets
-# Restore iptables
-# Restore fail2ban
-# Restart all
-# Cleanup
diff --git a/bin/ld-reinitialize b/bin/ld-reinitialize
--- a/bin/ld-reinitialize
+++ b/bin/ld-reinitialize
@@ -39,14 +39,13 @@
 #
 # OPTIONS:
 #   -c | --config
-#      Default = /etc/lockdown/conf/lockdown.conf
-#      Use given configuration files
+#      Provide alternate configuration file
 #   -d | --dry-run
 #      Echos the commands that would be executed rather than executing them
 #   -h | --help
 #      Run help function and exit
 #   -o | --out
-#      Location to save archives
+#      Location to save backup otherwise ./
 #   -s | --skip-f2b
 #      Do not reboot F2B configuration files
 #   -v | --verbose
@@ -60,6 +59,24 @@
 # Strict mode
 set -euo pipefail
 IFS=$'\n\t'
+
+# Instantiate variables
+BACKUP=1
+CONFIG='/etc/lockdown/conf/lockdown.conf'
+DATE=`date +%Y%m%d%H%M%S`
+DISTRO=''
+DOWNLOAD=1
+DRY_RUN=0
+EPEL='epel-release'
+FAIL2BAN='fail2ban'
+GAMIN='gamin'
+IPSET='ipset'
+IPTABLES='iptables'
+OUT=''
+PORTS=$ports
+SILENT=0
+VERBOSE=0
+YES=''
 
 # Help function
 help () { 
@@ -83,34 +100,255 @@ ORIGIN=`pwd`
 while :
 do
     case ${1:-} in
+      -d | --dry-run)
+      DRY_RUN='echo'
+      shift 1
+    ;;
       -h | --help)
       help
       shift 1
     ;;
+      -n | --no-download)
+      DOWNLOAD=0
+      shift 1
+    ;;
       -v | --verbose)
-    VERBOSE=true
-    shift 1
+      VERBOSE=1
+      shift 1
+    ;;
+      -x | --no-backup)
+      BACKUP=0
+      shift 1
+    ;;
+      -y | --yes)
+      YES='-y'
+      shift 1
     ;;
       -*)
-    echo "Error: Unknown option: $1" >&2
-    exit 1
+      echo "Error: Unknown option: $1" >&2
+      exit 1
     ;;
       *)  # No more options
-    break
+      break
     ;;
     esac
 done
 
-# Validate required arguments
+# Load configuration file
+if [ ! -f /etc/lockdown/conf/lockdown-default.conf ] && [ ! -f "$CONFIG" ]
+then
+  echo "Lockdown configuration files not found, cannot continue."
+  exit 1
+fi
+if [ -f "$SRCDIR/conf/lockdown-default.conf" ]
+then
+  . "$SRCDIR/conf/lockdown-default.conf"
+fi
+if [ -f "$CONFIG" ]
+then
+  . "$CONFIG"
+else
+  echo "Lockdown custom configuration file $CONFIG not found, cannot continue."
+  exit 1
+fi
 
-# Set necessary defaults
+# Ensure distro is supported
+determine_distro
+if [ -z "$DISTRO" ]
+then
+  echo "Could not determine distro, cannot continue."
+  echo "Please report this as a bug on Github, thanks!"
+  exit 1
+elif (( ! SILENT ))
+then
+  echo "$DISTRO discovered, proceeding with $PACKAGE_MANAGER"
+fi
+
+# Warn user unless using force
+if [ -z $YES ]
+then
+  echo "Lockdown is a sophisticated control system for a suite of sophisticated software."
+  echo "It's misuse or breakage can cause your system to become unusable or unable to"
+  echo "accept incoming traffic or send any out.  In the case of failures, you must be"
+  echo "capable of diagnosing and repairing any problems.  Lockdown is free software"
+  echo "provided as is and you are responsible for any effects or side-effects of it's"
+  echo "existence on your systems."
+  echo
+  echo "You are about to perform a reinitialization of Lockdown on `hostname` with"
+  echo "IP `curl -s whatip.gzo.com`.  This will stop your firewall related services,"
+  echo "overwrite their configurations and restart them.  By default, a backup tarball"
+  echo "will be saved in the current"
+  echo "directory."
+  echo
+  read -p "Are you sure you wish to proceed? [y/N] " -n 1 -r REPLY
+  if [[ $REPLY =~ ^[Yy]$ ]] ; then
+    echo
+    echo "Locking down `hostname`!"
+  else
+    echo "Exiting without making any changes."
+    exit 2
+  fi
+fi
 
 # Check verbosity
-if [ -v VERBOSE ] ; then
+if (( VERBOSE )) ; then
   set -v
 fi
 
+# Backup currently saved configuration
+if (( BACKUP ))
+then
+  $DRY_RUN ld-export
+fi
 
-# Stop all services
-# Re-run setup with -f, etc
-# Cleanup
+# Stop services
+$DRY_RUN pidof fail2ban && $DRY_RUN service fail2ban stop
+$DRY_RUN pidof iptables && $DRY_RUN service iptables stop
+$DRY_RUN pidof ipset && $DRY_RUN service ipset stop
+
+# Kill services if necessary
+$DRY_RUN pidof fail2ban && $DRY_RUN pidof fail2ban | $DRY_RUN xargs kill -9
+$DRY_RUN pidof iptables && $DRY_RUN pidof iptables | $DRY_RUN xargs kill -9
+$DRY_RUN pidof ipset && $DRY_RUN pidof ipset | $DRY_RUN xargs kill -9
+
+## Manipulate system daemons!!
+if (( ! SILENT )) ; then echo; fi
+case $DISTRO in
+  "Amazon Linux"|"CentOS")
+    lockdown_daemons_srvchkcnf
+  ;;
+  "Fedora"|"RHEL"|"Ubuntu")
+    lockdown_daemons_systemctl
+  ;;
+  *)  # No more options
+    echo "Unsupported distro, exiting."
+    exit 1
+  ;;
+esac
+if (( ! SILENT )) ; then echo; fi
+
+
+# Download latest lists
+if (( DOWNLOAD ))
+then
+  if (( ! SILENT ))
+  then
+    echo "Downloading latest blacklists & country CIDRs."
+  fi
+  $DRY_RUN /usr/local/sbin/ld-update-lists -f
+fi
+if (( ! SILENT )) ; then echo; fi
+
+## Initialize ipset
+# Clear IP set
+$DRY_RUN ipset flush
+$DRY_RUN ipset x
+
+# Process IP Set pre-process rules
+if [ -f "$SRCDIR/pre-process/ipset.rules" ]
+then
+  . "$SRCDIR/pre-process/ipset.rules" $SILENT
+elif (( ! SILENT ))
+then
+  echo "Rules file $1 not found, skipping"
+fi
+
+# Create sets
+$DRY_RUN ipset create blacklist-f2b hash:ip
+$DRY_RUN ipset create blacklist-ips hash:ip
+$DRY_RUN ipset create blacklist-net hash:net
+$DRY_RUN ipset create whitelist-ips hash:ip
+$DRY_RUN ipset create whitelist-net hash:net
+$DRY_RUN ipset create blacklist-countries hash:net
+$DRY_RUN ipset create whitelist-countries hash:net
+
+# Load list data into sets
+$DRY_RUN $location_bin/ld-load-lists
+
+# Process IP Set post-process rules
+if [ -f "$SRCDIR/post-process/ipset.rules" ]
+then
+  . "$SRCDIR/post-process/ipset.rules" $SILENT
+elif (( ! SILENT ))
+then
+  echo "Rules file $1 not found, skipping"
+fi
+
+## Initialize iptables
+# Flush nat, mangle, all chains
+$DRY_RUN iptables -t nat -F
+$DRY_RUN iptables -t mangle -F
+$DRY_RUN iptables -F
+# Delete non-default chains
+$DRY_RUN iptables -X
+# Set default policy to drop
+$DRY_RUN iptables -P INPUT DROP
+$DRY_RUN iptables -P FORWARD DROP
+$DRY_RUN iptables -P OUTPUT ACCEPT
+
+# Process IP Tables pre-process rules
+if [ -f "$SRCDIR/pre-process/iptables.rules" ]
+then
+  . "$SRCDIR/pre-process/iptables.rules" $SILENT
+elif (( ! SILENT ))
+then
+  echo "Rules file $1 not found, skipping"
+fi
+
+# Drop invalid packets
+$DRY_RUN iptables -I INPUT 1 -m conntrack --ctstate INVALID -j DROP
+# Allow all to/from loopback (lo)
+$DRY_RUN iptables -I INPUT 2 -i lo -j ACCEPT
+$DRY_RUN iptables -I OUTPUT 1 -i lo -j ACCEPT
+# Allow established & related incoming, for outgoing 
+# connections initiated from server
+$DRY_RUN iptables -I INPUT 3 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+# Create set matching rules
+$DRY_RUN iptables -I INPUT 4 -m set --match-set whitelist-ips -J ACCEPT
+$DRY_RUN iptables -I INPUT 5 -m set --match-set blacklist-ips -J DROP
+$DRY_RUN iptables -I INPUT 6 -m set --match-set whitelist-net -J ACCEPT
+$DRY_RUN iptables -I INPUT 7 -m set --match-set blacklist-net -J DROP
+$DRY_RUN iptables -I INPUT 8 -m set --match-set whitelist-countries -J ACCEPT
+$DRY_RUN iptables -I INPUT 9 -m set --match-set blacklist-countries -J DROP
+# Create global inlets
+for port in ${PORTS[@]}
+do
+  # This rule avoids connection tracking in favor of optimal processing 
+  # speed which is the same reason we allow all outgoing traffic rather 
+  # than just related - at small scale this would be a non-issue but at
+  # scale would definitely add a lot of extra cpu cycles in the long term
+  $DRY_RUN iptables -A INPUT -p tcp --dport $port -j ACCEPT
+  # If you were to use a drop target in the default outgoing policy, then
+  # you would want to add an established/related output rule here as well.
+done
+
+# Process IP Tables post-process rules
+if [ -f "$SRCDIR/post-process/iptables.rules" ]
+then
+  . "$SRCDIR/post-process/iptables.rules" $SILENT
+elif (( ! SILENT ))
+then
+  echo "Rules file $1 not found, skipping"
+fi
+
+
+# Installation complete, present results to user if applicable
+if [ $DRY_RUN ]
+then
+  # Dry run notification
+  echo
+  echo "*Notice*"
+  echo "You have run ld-install in dry run mode."
+  echo "If you run the same command line without -d or --dry-run again,"
+  echo "the commands above will be executed and permanent changes will be made."
+  echo
+  echo "Lockdown has *not* been installed and your system has not been altered!"
+elif (( ! SILENT ))
+then
+  # Checking installation
+  installation_report
+fi
+
+## w00t!
+exit 0
+
diff --git a/ld-install b/ld-install
--- a/ld-install
+++ b/ld-install
@@ -37,6 +37,8 @@
 #      Run help function and exit
 #   -n | --no-download
 #      Do not run commands to download latest blacklist & country CIDR lists
+#   -o | --out
+#      Output directory to save backup tarball
 #   -s | --silent
 #      Silent will attempt to prevent any and all output except in the event
 #      of failure.  Silent operation implies --yes and will not ask permission
@@ -63,23 +65,24 @@ IFS=$'\n\t'
 
 # Load configuration file
 SRCDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-if [ ! -f $SRCDIR/conf/lockdown-default.conf ] && [ ! -f $SRCDIR/conf/lockdown.conf ]
+if [ ! -f "$SRCDIR/conf/lockdown-default.conf" ] \
+  && [ ! -f "$SRCDIR/conf/lockdown.conf" ]
 then
   echo "Lockdown installation configuration file not found, cannot continue."
   exit 1
 fi
-if [ -f $SRCDIR/conf/lockdown-default.conf ]
+if [ -f "$SRCDIR/conf/lockdown-default.conf" ]
 then
-  . $SRCDIR/conf/lockdown-default.conf
+  . "$SRCDIR/conf/lockdown-default.conf"
 fi
-if [ -f $SRCDIR/conf/lockdown.conf ]
+if [ -f "$SRCDIR/conf/lockdown.conf" ]
 then
-  . $SRCDIR/conf/lockdown.conf
+  . "$SRCDIR/conf/lockdown.conf"
 fi
 
 # Instantiate Variables
 BACKUP=1
-DATE=`date +%Y%m%d%H%M%S`
+DATE=`date +%s`
 DISTRO=''
 DOWNLOAD=$update_lists
 DRY_RUN=''
@@ -90,225 +93,29 @@ IPSET='ipset'
 IPTABLES='iptables'
 PACKAGE_MANAGER='yum'
 PORTS=$ports
+SAVE_PATH=`pwd`
 SILENT=0
 YES=''
 
 # Save origin
 ORIGIN=`pwd`
 
-# Distro determination
-determine_distro () {
-  if [ -f /etc/os-release ]
-  then
-    if [[ `cut -d= -f2 /etc/os-release` =~ 'Amazon Linux' ]]
-    then
-      DISTRO='Amazon Linux'
-    elif [[ `cut -d= -f2 /etc/os-release` =~ 'CentOS' ]]
-    then
-      DISTRO='CentOS'
-    elif [[ `cut -d= -f2 /etc/os-release` =~ 'Fedora' ]]
-    then
-      DISTRO='Fedora'
-      PACKAGE_MANAGER='dnf'
-    elif [[ `cut -d= -f2 /etc/os-release` =~ 'RHEL' ]]
-    then
-      DISTRO='RHEL'
-    elif [[ `cut -d= -f2 /etc/os-release` =~ 'Red Hat' ]]
-    then
-      DISTRO='RHEL'
-    elif [[ `cut -d= -f2 /etc/os-release` =~ 'Ubuntu' ]]
-    then
-      DISTRO='Ubuntu'
-      PACKAGE_MANAGER='apt-get'
-    fi
-  elif [ -f /etc/system-release ]
-  then
-    if [[ `cut -d= -f2 /etc/system-release` =~ 'CentOS' ]]
-    then
-      DISTRO='CentOS'
-    fi
-  fi
-}
 
 # Help function
 help () { 
   echo "Description:"
-  echo "  XXX"
+  echo "  Running this program will install Lockdown and all related services,"
+  echo "  configuration files and lists."
   echo "Usage:"
-  echo "  `basename $0` [-f] [-v]"
-  echo "  `basename $0` [--force] [--verbose]"
+  echo "  `basename $0` [-d] [-n] [-s] [-v] [-y]"
+  echo "  `basename $0` [--dry-run] [--no-download] [--silent] [--verbose] [--yes]"
   exit 0
 }
 
-# Lockdown initialization
-init_lockdown () {
-  if [ ! -d /usr/local/sbin ]
-  then
-    mkdir -p /usr/local/sbin
-  fi
-  if [ -d /usr/local/sbin ]
-  then
-    chmod u+x bin/*
-    cp bin/* /usr/local/sbin
-  else
-    echo "Could not create or access /usr/local/sbin, installation cannot continue"
-    exit 1
-  fi
-  if [ ! -d /etc/lockdown ]
-  then
-    mkdir -p /etc/lockdown
-  fi
-  if [ -d /etc/lockdown ]
-  then
-    cp -r blacklist-ips /etc/lockdown
-    cp -r blacklist-networks /etc/lockdown
-    cp -r conf /etc/lockdown
-    cp -r fail2ban /etc
-    cp -r lists /etc/lockdown
-    cp -r post-process /etc/lockdown
-    cp -r pre-process /etc/lockdown
-    cp -r whitelist-ips /etc/lockdown
-    cp -r whitelist-networks /etc/lockdown
-  else
-    echo "Could not create or access /etc/lockdown, installation cannot continue"
-    exit 1
-  fi
-  if [ ! -d /usr/local/share/lockdown ]
-  then
-    mkdir -p /usr/local/share/lockdown
-  fi
-  if [ -d /usr/local/share/lockdown ]
-  then
-    cp -r lists/* /usr/local/share/lockdown
-  else
-    echo "Could not create or access /usr/local/share/lockdown, installation cannot continue"
-    exit 1
-  fi
-}
-
-# Report installation status
-installation_report () {
-  # Check for executables & required directories
-  if [ -f /usr/bin/iptables ]
-  then
-    echo "/usr/bin/iptables found"
-  else
-    "Could not find iptables, please report on Github issues"
-    exit 1
-  fi
-  if [ -f /usr/sbin/ipset ]
-  then
-    echo "/usr/sbin/ipset found"
-  else
-    "Could not find ipset, please report on Github issues"
-    exit 1
-  fi
-  if [ -f /usr/bin/fail2ban-client ]
-  then
-    echo "/usr/bin/fail2ban-client found"
-  else
-    echo "Could not find fail2ban, please report on Github issues"
-    exit 1
-  fi
-  if [ -d /etc/fail2ban ]
-  then
-    echo "/etc/fail2ban found"
-  else
-    "Could not find fail2ban configuration files, please report on Github issues"
-    exit 1
-  fi
-  if [ -d /etc/lockdown ]
-  then
-    echo "/etc/lockdown found"
-  else
-    "Could not find Lockdown configuration files, please report on Github issues"
-    exit 1
-  fi
-  if [ -d /usr/share/lockdown ]
-  then
-    echo "/usr/share/lockdown found"
-  else
-    "Could not find Lockdown lists, please report on Github issues"
-    exit 1
-  fi
-  if [ -f /usr/local/sbin/ld-allow ]
-  then
-    echo "/etc/lockdown found"
-  else
-    "Could not find Lockdown configuration files, please report on Github issues"
-    exit 1
-  fi
-
-  # Check required services are running
-  if (( `pidof nftables` ))
-  then
-    "nftables process found, please report on Github issues"
-    exit 1
-  else
-    echo "nftables not running"
-  fi
-  if (( `pidof firewalld` ))
-  then
-    "firewalld process found, please report on Github issues"
-    exit 1
-  else
-    echo "firewalld not running"
-    exit 1
-  fi
-
-  # Check required services are running
-  if (( `pidof iptables` ))
-  then
-    echo "iptables is running"
-  else
-    "iptables process not found, please report on Github issues"
-    exit 1
-  fi
-  if (( `pidof ipset` ))
-  then
-    echo "ipset is running"
-  else
-    "ipset process not found, please report on Github issues"
-    exit 1
-  fi
-  if (( `pidof fail2ban-server` ))
-  then
-    echo "fail2ban-server is running"
-  else
-    "fail2ban-server process not found, please report on Github issues"
-    exit 1
-  fi
-
-  # Make sure everything is A-OK (ld-test should exit 0 status w/no output)
-  if (( `/usr/local/sbin/ld-test` ))
-  then
-    "Lockdown test failed, please report on Github issues"
-    exit 1
-  else
-    echo "Lockdown test passed."
-  fi
-
-  # Display success message and show user relevant files
-  echo
-  echo
-  echo "Success!"
-  echo "Lockdown executables are in /usr/local/sbin and start with ld-"
-  echo "ls /usr/local/sbin/ld-*:"
-  ls /usr/local/sbin/ld-*
-  echo "Lockdown configuration files are in /etc/lockdown"
-  echo "ls /etc/lockdown:"
-  ls /etc/lockdown
-  echo "Lockdown blacklist & country files are in /usr/share/lockdown"
-  echo "ls /usr/share/lockdown:"
-  ls /usr/share/lockdown
-  echo
-  echo "May the force of my ban hammer be with you! - @iDoMeteor"
-}
-
-# Check for arguments or provide help
-if [ $# -eq 0 ] ; then
-  help
-fi
+# Load libraries
+. lib/determine_linux_distro.fnc
+. lib/lockdown_init.fnc
+. lib/lockdown_installation_report.fnc
 
 # Parse command line arguments into variables
 while :
@@ -330,6 +137,10 @@ do
       SILENT=1
       YES='-y'
       shift 1
+    ;;
+      -o | --out)
+      SAVE_PATH=$2
+      shift 2
     ;;
       -v | --verbose)
       VERBOSE=true
@@ -353,11 +164,6 @@ do
     esac
 done
 
-# Check verbosity
-if [ -v VERBOSE ] ; then
-  set -v
-fi
-
 # Ensure distro is supported
 determine_distro
 if [ -z "$DISTRO" ]
@@ -368,9 +174,10 @@ then
 elif (( ! SILENT ))
 then
   echo "$DISTRO discovered, proceeding with $PACKAGE_MANAGER"
+  echo
 fi
 
-# Warn user unless using force
+# Warn user unless they've agreed to everything
 if [ -z $YES ]
 then
   echo "Lockdown is a sophisticated control system for a suite of sophisticated software."
@@ -380,8 +187,8 @@ then
   echo "provided as is and you are responsible for any effects or side-effects of it's"
   echo "existence on your systems."
   echo
-  echo "You are about to perform this installation on `hostname`."
-  echo "`curl -s whatip.gzo.com`."
+  echo "You are about to perform this installation on `hostname` with"
+  echo "IP `curl -s whatip.gzo.com`."
   echo
   read -p "Proceed with installation and configuration of Lockdown and all related services? [y/N] " -n 1 -r REPLY
   if [[ $REPLY =~ ^[Yy]$ ]] ; then
@@ -393,27 +200,39 @@ then
   fi
 fi
 
+# Check verbosity
+if [ -v VERBOSE ]
+then
+  set -v
+fi
+
 # Attempt to back up pre-existing configuration files, this is similar
 # to what ld-export does but does not attempt to save a running configuration.
+if [ ! -d /etc/fail2ban ] && \
+   [ ! -f /etc/ipset.conf ] && \
+   [ ! -d /etc/lockdown ] && \
+   [ ! -d /etc/sysconfig/ip?tables.* ]
+then
+  BACKUP=0
+fi
 if (( BACKUP ))
 then
-  $DRY_RUN mkdir -p "./bak/$DATE" && \
-  $DRY_RUN cp -r \
+  # Check temp location
+  if [ ! -d "$SAVE_PATH" ]
+  then
+    if (( ! SILENT )) ; then echo "Output location $SAVE_PATH does not exist, creating"; fi
+    mkdir -p "$SAVE_PATH"
+  fi
+  $DRY_RUN tar czf "$SAVE_PATH/ld-pre-install-backup-$DATE.tar.gz" \
     /etc/fail2ban* \
-    /etc/ip6tables* \
     /etc/ipset* \
-    /etc/iptables* \
     /etc/lockdown* \
-    /etc/sysconfig/ip6tables* \
-    /etc/sysconfig/iptables* \
-    "./bak/$DATE"
-  $DRY_RUN tar czf "./bak/$DATE-ld-pre-install.tar.gz" "./bak/$DATE"
+    /etc/sysconfig/ip?tables*
 fi
 
 ## Begin Installations!!
 if [ 'yum' = $PACKAGE_MANAGER ] || [ 'dnf' = $PACKAGE_MANAGER ]
 then
-  # TODO: Check if this is already installed
   $DRY_RUN $PACKAGE_MANAGER install $YES $EPEL
 fi
 if [ ! -f /usr/bin/iptables ]
@@ -432,7 +251,7 @@ if [ ! -f /usr/lib64/libgamin-1.so.0 ]
 then
   $DRY_RUN $PACKAGE_MANAGER install $YES $GAMIN
 fi
-$DRY_RUN init_lockdown $YES
+$DRY_RUN lockdown_init $YES
 
 ## Manipulate system daemons!!
 # This is done in the following order for maximum safety
@@ -447,40 +266,65 @@ case $DISTRO in
     #   Amazon Linux, CentOS
     #     service x start|stop|etc
     #     chkconfig x on|off
+    # Begin starting services
     if (( ! SILENT )) ; then echo "Starting services for $DISTRO"; fi
     $DRY_RUN service fail2ban start
     if [ 0 -ne $? ] && [ -z $DRY_RUN ]
     then
         echo "Failed to start fail2ban, exiting."
         exit 1
+    else
+      echo "Started fail2ban"
     fi
     $DRY_RUN service ipset start
     if [ 0 -ne $? ] && [ -z $DRY_RUN ]
     then
         echo "Failed to start ipset, exiting."
         exit 1
+    else
+      echo "Started ipset"
     fi
+echo "Trying iptables"
+    echo $DRY_RUN service iptables start
     $DRY_RUN service iptables start
-    if [ 0 -ne $? ] && [ -z $DRY_RUN ]
+echo "Tried iptables"
+echo $?
+    if [ 1 -eq $? ] && [ -z $DRY_RUN ]
     then
         echo "Failed to start iptables, exiting."
         exit 1
+    else
+      echo "Started iptables"
     fi
+    # Begin stopping & disabling conflicting services
+    if [ `pidof nftables` ]
+    then
+      if (( ! SILENT )) ; then echo "Stopping & disabling nftables"; fi
+      $DRY_RUN service nftables stop
+      $DRY_RUN chkconfig nftables off
+    fi
+    if [ `pidof firewalld` ]
+    then
+      if (( ! SILENT )) ; then echo "Stopping & disabling firewalld"; fi
+      $DRY_RUN service firewalld stop
+      $DRY_RUN chkconfig firewalld off
+    fi
+    # Begin enabling services
     if (( ! SILENT )) ; then echo "Enabling services for $DISTRO"; fi
     $DRY_RUN chkconfig fail2ban on
-    if (( `chkconfig fail2ban` )) && [ -z $DRY_RUN ]
+    if [ 0 -ne $? ] && [ -z $DRY_RUN ]
     then
         echo "Failed to enable fail2ban, exiting."
     fi
     $DRY_RUN chkconfig ipset on
-    if (( `chkconfig ipset` )) && [ -z $DRY_RUN ]
+    if [ 0 -ne $? ] && [ -z $DRY_RUN ]
     then
-        echo "Failed to enable fail2ban, exiting."
+        echo "Failed to enable ipset, exiting."
     fi
     $DRY_RUN chkconfig iptables on
-    if (( `chkconfig iptables` )) && [ -z $DRY_RUN ]
+    if [ 0 -ne $? ] && [ -z $DRY_RUN ]
     then
-        echo "Failed to enable fail2ban, exiting."
+        echo "Failed to enable iptables, exiting."
     fi
     if (( ! SILENT )) ; then echo "Service configuration completed successfully!"; fi
   ;;
@@ -488,6 +332,7 @@ case $DISTRO in
     #   Fedora, RHEL, Ubuntu
     #     systemctl start|stop|etc x
     #     systemctl enable|disable x
+    # Begin starting services
     if (( ! SILENT )) ; then echo "Starting systemctl starts for $DISTRO"; fi
     $DRY_RUN systemctl start fail2ban
     if [ 0 -ne $? ] && [ -z $DRY_RUN ]
@@ -507,6 +352,20 @@ case $DISTRO in
         echo "Failed to start iptables, exiting."
         exit 1
     fi
+    # Begin stopping & disabling conflicting services
+    if [ `pidof nftables` ]
+    then
+      if (( ! SILENT )) ; then echo "Stopping & disabling nftables"; fi
+      $DRY_RUN systemctl stop nftables
+      $DRY_RUN systemctl disable nftables
+    fi
+    if [ `pidof firewalld` ]
+    then
+      if (( ! SILENT )) ; then echo "Stopping & disabling firewalld"; fi
+      $DRY_RUN systemctl stop nftables
+      $DRY_RUN systemctl disable nftables
+    fi
+    # Begin enabling services
     if (( ! SILENT )) ; then echo "Enabling services for $DISTRO"; fi
     $DRY_RUN systemctl enable fail2ban
     if (( `systemctl is-enabled fail2ban` )) && [ -z $DRY_RUN ]
@@ -552,7 +411,8 @@ $DRY_RUN ipset x
 if [ -f "$SRCDIR/pre-process/ipset.rules" ]
 then
   . "$SRCDIR/pre-process/ipset.rules" $SILENT
-elif (( ! $2 ))
+elif (( ! SILENT ))
+then
   echo "Rules file $1 not found, skipping"
 fi
 
@@ -572,7 +432,8 @@ $DRY_RUN $location_bin/ld-load-lists
 if [ -f "$SRCDIR/post-process/ipset.rules" ]
 then
   . "$SRCDIR/post-process/ipset.rules" $SILENT
-elif (( ! $2 ))
+elif (( ! SILENT ))
+then
   echo "Rules file $1 not found, skipping"
 fi
 
@@ -592,7 +453,8 @@ $DRY_RUN iptables -P OUTPUT ACCEPT
 if [ -f "$SRCDIR/pre-process/iptables.rules" ]
 then
   . "$SRCDIR/pre-process/iptables.rules" $SILENT
-elif (( ! $2 ))
+elif (( ! SILENT ))
+then
   echo "Rules file $1 not found, skipping"
 fi
 
@@ -627,7 +489,8 @@ done
 if [ -f "$SRCDIR/post-process/iptables.rules" ]
 then
   . "$SRCDIR/post-process/iptables.rules" $SILENT
-elif (( ! $2 ))
+elif (( ! SILENT ))
+then
   echo "Rules file $1 not found, skipping"
 fi
 
