Some touch ups, added cron job, drafting updater

diff --git a/ld-update b/ld-update
--- a/ld-update
+++ b/ld-update
@@ -1,10 +1,10 @@
 #!/bin/bash
-#ld-install
+#ld-update
 
 #===============================================================================
 #
 # FILE: 
-#   ld-install
+#   ld-update
 #
 # REVISION:  
 #   001
@@ -12,11 +12,11 @@
 # WHEN TO USE:  
 #   When you are very sure you want to boot up the full Lockdown suite of
 #   utilities using the configuration files in the conf/ directory where
-#   ld-install is located.
+#   ld-update is located.
 #
 # USAGE: 
-#   ld-install [-d] [-n] [-s] [-v] [-y]
-#   ld-install [--dry-run] [--no-download] [--silent] [--verbose] [--yes]
+#   ld-update [-d] [-n] [-s] [-v] [-y]
+#   ld-update [--dry-run] [--no-download] [--silent] [--verbose] [--yes]
 #
 # DESCRIPTION:
 #   This script will try to do all of the following things, 
@@ -510,3 +510,73 @@ fi
 
 ## w00t!
 exit 0
+
+  # Ensure all relevant directories exist, copy new executables and new default
+  # configuration file into place, and copy everything to /usr/share/lockdown
+  if [ ! -d /usr/sbin ]
+  then
+    mkdir -p /usr/sbin
+  fi
+  if [ -d /usr/sbin ]
+  then
+    chmod u+x bin/*
+    cp bin/* /usr/sbin
+  else
+    echo "Could not create or access /usr/sbin, installation cannot continue"
+    exit 1
+  fi
+  if [ ! -d /etc/lockdown ]
+  then
+    mkdir -p /etc/lockdown
+  fi
+  if [ ! -d /etc/lockdown/archives ]
+  then
+    mkdir -p /etc/lockdown/archives
+  fi
+  if [ ! -d /etc/lockdown/blacklist-ips ]
+  then
+    mkdir -p /etc/lockdown/blacklist-ips
+    touch /etc/lockdown/blacklist-ips/entries.txt
+  fi
+  if [ ! -d /etc/lockdown/blacklist-net ]
+  then
+    mkdir -p /etc/lockdown/blacklist-net
+    touch /etc/lockdown/blacklist-net/entries.txt
+  fi
+  if [ ! -d /etc/lockdown/whitelist-ips ]
+  then
+    mkdir -p /etc/lockdown/whitelist-ips
+    touch /etc/lockdown/whitelist-ips/entries.txt
+  fi
+  if [ ! -d /etc/lockdown/whitelist-net ]
+  then
+    mkdir -p /etc/lockdown/whitelist-net
+    touch /etc/lockdown/whitelist-net/entries.txt
+  fi
+  if [ -d /etc/lockdown ]
+  then
+    /bin/cp -r lists /etc/lockdown
+    /bin/cp -r conf /etc/lockdown
+    /bin/cp -r lists /etc/lockdown
+    /bin/cp -r post-process /etc/lockdown
+    /bin/cp -r pre-process /etc/lockdown
+    /bin/cp -r etc/ipset.conf /etc/
+    chown root:root /etc/ipset.conf
+    /bin/cp -r etc/init.d/ipset /etc/init.d
+    chown -R root:root /etc/lockdown /etc/init.d/ipset
+    chmod u+x /etc/init.d/ipset
+  else
+    echo "Could not create or access /etc/lockdown, installation cannot continue"
+    exit 1
+  fi
+  if [ ! -d /usr/local/share/lockdown ]
+  then
+    mkdir -p /usr/local/share/lockdown
+  fi
+  if [ -d /usr/local/share/lockdown ]
+  then
+    cp -r . /usr/local/share/lockdown/
+  else
+    echo "Could not create or access /usr/local/share/lockdown, installation cannot continue"
+    exit 1
+  fi
