Added beta support for Amazon Linux 2

diff --git a/lib/lockdown_init b/lib/lockdown_init
--- a/lib/lockdown_init
+++ b/lib/lockdown_init
@@ -60,13 +60,19 @@ lockdown_init () {
   fi
   if [ -d /etc/systemd ]
   then
+    echo "Upstart discovered, installing service units"
     /bin/cp -r usr/* /usr/
     chown -R root:root /usr/libexec/ip* /usr/lib/systemd/system/ip*
     chmod u+x /usr/libexec/iptables/* /usr/libexec/ipset/ipset.start-stop /usr/lib/systemd/system/ip*
-  else
+  elif [ -d /etc/init.d ]
+  then
+    echo "SysV init discovered, installing init files"
     /bin/cp etc/init.d/ipset /etc/init.d/
     chown -R root:root /etc/lockdown /etc/init.d/ipset
     chmod u+x /etc/init.d/ipset
+  else
+    echo "Could not determine system initialization method, cannot continue"
+    exit 1
   fi
   if [ ! -d /usr/local/share/lockdown ]
   then
