Beta 2 for Amazon Linux 2

diff --git a/lib/lockdown_reinit b/lib/lockdown_reinit
--- a/lib/lockdown_reinit
+++ b/lib/lockdown_reinit
@@ -55,24 +55,41 @@ lockdown_reinit () {
     then
       /bin/rm -r /etc/lockdown/lists
     fi
-    /bin/cp -r conf /etc/lockdown
-    /bin/cp -r lists /etc/lockdown
-    /bin/cp -r post-process /etc/lockdown
-    /bin/cp -r pre-process /etc/lockdown
-    /bin/cp -r etc/ipset.conf /etc/
+    /bin/cp -r $SRCDIR/conf /etc/lockdown
+    /bin/cp -r $SRCDIR/lists /etc/lockdown
+    /bin/cp -r $SRCDIR/post-process /etc/lockdown
+    /bin/cp -r $SRCDIR/pre-process /etc/lockdown
+    /bin/cp -r $SRCDIR/etc/ipset.conf /etc/
     chown root:root /etc/ipset.conf
   else
-    echo "Could not create or access /etc/lockdown, installation cannot continue"
+    echo "Could not create or access /etc/lockdown, re-initilization cannot continue"
     exit 1
   fi
   if [ -d /etc/systemd ]
   then
-    /bin/cp -r usr/* /usr/
+    echo "Upstart discovered, updating service units"
+    /bin/cp -r $SRCDIR/usr/* /usr/
     chown -R root:root /usr/libexec/ip* /usr/lib/systemd/system/ip*
     chmod u+x /usr/libexec/iptables/* /usr/libexec/ipset/ipset.start-stop /usr/lib/systemd/system/ip*
-  else
-    /bin/cp etc/init.d/ipset /etc/init.d/
+  elif [ -d /etc/init.d ]
+  then
+    echo "SysV init discovered, updating init files"
+    /bin/cp $SRCDIR/etc/init.d/ipset /etc/init.d/
     chown -R root:root /etc/lockdown /etc/init.d/ipset
     chmod u+x /etc/init.d/ipset
+  else
+    echo "Could not determine system initialization method, cannot continue"
+    exit 1
+  fi
+  if [ ! -d /usr/local/share/lockdown ]
+  then
+    mkdir -p /usr/local/share/lockdown
+  fi
+  if [ -d /usr/local/share/lockdown ]
+  then
+    /bin/cp -r $SRCDIR/* /usr/local/share/lockdown/
+  else
+    echo "Could not create or access /usr/local/share/lockdown, installation cannot continue"
+    exit 1
   fi
 }
